"""Continuity Director ComfyUI custom node package."""

from .nodes import NODE_CLASS_MAPPINGS as BASE_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as BASE_NODE_DISPLAY_NAME_MAPPINGS
from .extended_nodes import NODE_CLASS_MAPPINGS as EXTENDED_NODE_CLASS_MAPPINGS
from .extended_nodes import NODE_DISPLAY_NAME_MAPPINGS as EXTENDED_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**BASE_NODE_CLASS_MAPPINGS, **EXTENDED_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **BASE_NODE_DISPLAY_NAME_MAPPINGS,
    **EXTENDED_NODE_DISPLAY_NAME_MAPPINGS,
}
WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
__version__ = "0.8.6"
